### PR TITLE
fix: CDI 4.0, removed DeltaSpike, switched to Weld Junit extension

### LINKED ISSUE #414: Replace DeltaSpike snapshot version with a stable one
CDI 15.0 is Jakarta EE 9.0 compatible, but it uses DeltaSpike [1.9.7-SNAPSHOT](https://github.com/vaadin/cdi/blob/44a2598f5125ebbfda9854dfc762c0c770c5545a/pom.xml#L50) version.
The stable version is requested in this [ticket](https://issues.apache.org/jira/browse/DELTASPIKE-1434), but the release date is unknown.
Possible solutions are:
- do the conversion by ourselves and include https://github.com/apache/deltaspike sources into CDI add-on,
- fork from https://github.com/apache/deltaspike , convert and release `com.vaadin.external.*` version,
- replace with Jakarta EE 9.0 compatible implementation, like for instance, this [community ported version](https://github.com/atbashEE/deltaspike-jakarta).

### PR DESCRIPTION
**Pull request by MarcinVaadin**
Updated to CDI 4.0, removed DeltaSpike dependencies, switched to Weld Junit 5 extension for running CDI unit tests.

DeltaSpike and OpenWebBeans support has been removed due to Jakarta and CDI 4.0 incompatibility.

Fixes #414

### CODE REVIEW

File: vaadin-cdi/src/main/java/com/vaadin/cdi/util/AnyLiteral.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+ */
+package com.vaadin.cdi.util;
+
+import jakarta.enterprise.inject.Any;
+import jakarta.enterprise.util.AnnotationLiteral;
+
+public class AnyLiteral extends AnnotationLiteral<Any> implements Any
+{
+    private static final long serialVersionUID = -8623640277155878657L;
+}
```
Comment (mshabarov) [inline vaadin-cdi/src/main/java/com/vaadin/cdi/util/AnyLiteral.java:27]:
```suggestion
}

```

File: vaadin-cdi/src/main/java/com/vaadin/cdi/util/ContextualInstanceInfo.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+
+    /**
+     * @param contextualInstance the contextual instance itself
+     */
+    public void setContextualInstance(T contextualInstance)
+    {
+        this.contextualInstance = contextualInstance;
+    }
+
+}
```
Comment (mshabarov) [inline vaadin-cdi/src/main/java/com/vaadin/cdi/util/ContextualInstanceInfo.java:76]:
```suggestion
}

```

**Review by mshabarov — DISMISSED** [review]

**Review by mshabarov — APPROVED** [review]
